### ISSUE TITLE
Possible to avoid hard dependency on audubon?

### ISSUE THREAD

**Issue by barracuda156** [paithiov909/gibasa#24]
`audubon` needs V8, which is broken for some platforms.

**Comment by paithiov909** [comment]
I agree that the installation of the V8 package sometimes frustrates us.

We can move only the functions we need to gibasa, since the functions in the audubon package that depend on V8 are not needed.

If there are more requests to do so, I'll consider it again.

**Comment by barracuda156** [comment]
> We can move only the functions we need to gibasa, since the functions in the audubon package that depend on V8 are not needed.

That would be awesome.

I wanted to add `gibasa` to Macports, but we need to avoid depending on V8 for that (since V8 is broken for some of platforms we support).
